[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Devin-Yeung/reprise"

[workspace.dependencies]
typed-builder = "0.23"
thiserror = "2"
clap = { version = "4.6", features = ["derive"] }
reprise = { path = "crates/reprise", version = "0.1.0" }
reprise-api = { path = "crates/reprise-api", version = "0.1.0" }
bollard = { version = "0.21.1", default-features = false, features = ["pipe", "http", "ssl"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
