[package]
name = "reprise-oci"
description = "Prepare root filesystems for Reprise OCI bundles."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
oci-spec = "0.10.0"
thiserror.workspace = true

[lints]
workspace = true
