[package]
name = "reprise-api"
description = "Public interface for Reprise: suspended, resumable sandboxes."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
typed-builder.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta = { version = "1", features = ["json"] }
serde_json = "1"

[lints]
workspace = true
