[package]
name = "reprise-runsc"
description = "Typed, blocking interface to the runsc CLI."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
thiserror.workspace = true
typed-builder = "0.23.2"

[dev-dependencies]
insta = "1.49.0"

[lints]
workspace = true
